name: Generate Snake

# Ishga tushish vaqtlari (har 6 soatda ishga tushadi)
on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:  # GitHub Actions sahifasidan qo‘lda ishga tushirishga ruxsat beradi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Reponi klonlash
      - uses: actions/checkout@v4

      # Snake generatorni ishlatish
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: oybek1100
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Git statusni tekshirish
      - run: git status

      # O‘zgarishlarni commit va push qilish
      - name: Commit and Push changes
        uses: github-actions-x/commit@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: "Update snake contribution animation"

      # GitHub Pagesga yuklash
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
